spring.application.name=Edu

# Database credentials are provided through environment variables.
spring.datasource.url=jdbc:postgresql://ep-proud-truth-axoc6ugl-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=	npg_SBG5dZP2jDLh

# JPA gère le schéma (évite les conflits avec schema.sql)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Pas d'init SQL manuel (les tables sont créées par Hibernate)
spring.sql.init.mode=never

server.port=${PORT:8003}
server.error.include-message=always
